### PR TITLE
remove successful invocations from queue

### PR DESCRIPTION
**Pull request by ghostnumber7**
According to the [docs](https://docs.aws.amazon.com/lambda/latest/operatorguide/sqs-retries.html), a queue will retry executions that throw an error, and remove from the queue executions that don't. 
This PR attempts to reproduce that behavior by:
1) invoking lambda with `RequestResponse` as `InvocationType`. This way we can know if it threw or not (also stops serverless-offline from restarting itself on error)
2) after we get response, we check if it contains an `FunctionError` property, that does not exist on successful executions

### CODE REVIEW

**Comment by ghostnumber7** [comment]
@gevorggalstyan you made a small mistake when refactoring the code [here](https://github.com/93v/sls-plugin-sqs-offline/blob/main/src/index.ts#L289). Response code is 200 even when the invocation fails when using `RequestResponse`. That's the reason behind validating with [this](https://github.com/93v/sls-plugin-sqs-offline/pull/46/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R288) instead of the status code, and due to this, the feature is not working (not retrying at all when lambda fails)

**Comment by gevorggalstyan** [comment]
hey @ghostnumber7, thank you for the heads up. I have also noticed that. I am reworking that part. Will probably have a working version in 2-3 weeks. Please keep your eye on it.

**Comment by ghostnumber7** [comment]
> hey @ghostnumber7, thank you for the heads up. I have also noticed that. I am reworking that part. Will probably have a working version in 2-3 weeks. Please keep your eye on it.

Yeah just saw that as I updated to the published version. it's working on 1.3.0 so I installed that version for now

**Comment by gevorggalstyan** [comment]
Hey @ghostnumber7 check out the latest version of the library. It now supports the latest concept of https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#services-sqs-batchfailurereporting

**Comment by ghostnumber7** [comment]
cool! thats a nice feature to have!

**Pull request merged**
